/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.calendar.frontend;

import cz.muni.fi.pv168.calendar.backend.Attendance;
import cz.muni.fi.pv168.calendar.backend.Event;
import cz.muni.fi.pv168.calendar.backend.Person;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Jan Smerda, Jiri Stary
 */
public class EventAttendance extends javax.swing.JDialog {

    private static Event event;

    /**
     * Creates new form EventAttendance
     */
    public EventAttendance(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTableAttendance.getColumnModel().getColumn(0).setMinWidth(0);
        jTableAttendance.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAttendance = new javax.swing.JTable();
        jButtonAttendanceCreatePerson = new javax.swing.JButton();
        jComboBoxNames = new javax.swing.JComboBox();
        jButtonAttendanceAdd = new javax.swing.JButton();
        jSpinnerAttendanceMonth = new javax.swing.JSpinner();
        jSpinnerAttendanceDay = new javax.swing.JSpinner();
        jSpinnerAttendanceYear = new javax.swing.JSpinner();
        jSpinnerAttendanceHour = new javax.swing.JSpinner();
        jSpinnerAttendanceMinute = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonAttendanceEdit = new javax.swing.JButton();
        jButtonAttendanceDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTableAttendance.setModel(new AttendanceTableModel());
        jScrollPane1.setViewportView(jTableAttendance);

        jButtonAttendanceCreatePerson.setText("Create new person");
        jButtonAttendanceCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendanceCreatePersonActionPerformed(evt);
            }
        });

        jComboBoxNames.setModel(new PersonComboBoxModel());
        jComboBoxNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNamesActionPerformed(evt);
            }
        });

        jButtonAttendanceAdd.setText("Add");
        jButtonAttendanceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendanceAddActionPerformed(evt);
            }
        });

        jSpinnerAttendanceMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinnerAttendanceDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinnerAttendanceYear.setModel(new javax.swing.SpinnerNumberModel(2014, 1970, 2100, 1));

        jSpinnerAttendanceHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jSpinnerAttendanceMinute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel1.setText("Person:");

        jLabel2.setText("Day:");

        jLabel3.setText("Month:");

        jLabel4.setText("Year:");

        jLabel5.setText("Hour:");

        jLabel6.setText("Minute:");

        jButtonAttendanceEdit.setText("Edit");
        jButtonAttendanceEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendanceEditActionPerformed(evt);
            }
        });

        jButtonAttendanceDelete.setText("Delete");
        jButtonAttendanceDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendanceDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAttendanceCreatePerson)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxNames, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerAttendanceDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerAttendanceMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerAttendanceYear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerAttendanceHour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinnerAttendanceMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonAttendanceDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                            .addComponent(jButtonAttendanceEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonAttendanceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonAttendanceCreatePerson)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAttendanceAdd)
                            .addComponent(jSpinnerAttendanceDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAttendanceMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAttendanceYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAttendanceHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAttendanceMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAttendanceEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAttendanceDelete)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNamesActionPerformed

    private void jButtonAttendanceCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendanceCreatePersonActionPerformed
        CreateEditPerson.start(null);
    }//GEN-LAST:event_jButtonAttendanceCreatePersonActionPerformed

    private void jButtonAttendanceDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendanceDeleteActionPerformed
        try {
            Attendance attendance = EventsMainWindow.getAttendanceManager()
                    .getAttendanceById((Integer) jTableAttendance.getValueAt(jTableAttendance.getSelectedRow(), 0));
            EventsMainWindow.getAttendanceManager().deleteAttendance(attendance);
            loadAttendanceDatabase();
            loadComboBox();  
        } catch (ArrayIndexOutOfBoundsException ex) {
            String msg = "No attendance is selected.";
            //logger.log(Level.SEVERE, msg, ex);
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_jButtonAttendanceDeleteActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        loadAttendanceDatabase();
        loadComboBox();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonAttendanceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendanceAddActionPerformed
        PersonComboBoxModel model = (PersonComboBoxModel) jComboBoxNames.getModel();
        
        Calendar calendar = new GregorianCalendar(
            (int) jSpinnerAttendanceYear.getValue(),
            (int) jSpinnerAttendanceMonth.getValue() - 1,
            (int) jSpinnerAttendanceDay.getValue(),
            (int) jSpinnerAttendanceHour.getValue(),
            (int) jSpinnerAttendanceMinute.getValue());
        Date date = calendar.getTime(); 
        
        int index = jComboBoxNames.getSelectedIndex();
        
        Attendance attendance = new Attendance();
        attendance.setEvent(event);       
        attendance.setPerson((Person) model.getSelectedPerson(index));
        attendance.setPlannedArrivalTime(date);
        EventsMainWindow.getAttendanceManager().createAttendance(attendance);

        loadAttendanceDatabase();
        loadComboBox();        
    }//GEN-LAST:event_jButtonAttendanceAddActionPerformed

    private void jButtonAttendanceEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendanceEditActionPerformed
        
    }//GEN-LAST:event_jButtonAttendanceEditActionPerformed

    public void loadAttendanceDatabase() {
        AttendanceLoadWorker attendanceLoadWorker = new AttendanceLoadWorker();
        attendanceLoadWorker.execute();
    }

    private class AttendanceLoadWorker extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            AttendanceTableModel model = (AttendanceTableModel) jTableAttendance.getModel();
            model.deleteAllAttendances();
            List<Attendance> attendances = new ArrayList<Attendance>();
            attendances = EventsMainWindow.getAttendanceManager().findAttendancesForEvent(event);

            for (Attendance a : attendances) {
                model.addAttendance(a);
            }
            return null;
        }
    }

    public void loadComboBox() {
        ComboBoxLoadWorker comboBoxLoadWorker = new ComboBoxLoadWorker();
        comboBoxLoadWorker.execute();
    }

    private class ComboBoxLoadWorker extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            PersonComboBoxModel modelPerson = (PersonComboBoxModel) jComboBoxNames.getModel();
            modelPerson.deleteAllPersons();            
            List<Person> persons = new ArrayList<Person>();
            persons = EventsMainWindow.getPersonManager().findAllPersons();
            
            AttendanceTableModel modelAttendance = (AttendanceTableModel) jTableAttendance.getModel();
            modelAttendance.deleteAllAttendances();
            List<Attendance> attendances = new ArrayList<Attendance>();
            attendances = EventsMainWindow.getAttendanceManager().findAttendancesForEvent(event);
            
            // remove persons that are already added
            for (Attendance a : attendances) {
                persons.remove(a.getPerson());
            }
            
            for (Person p : persons) {
                modelPerson.addPerson(p);
            }

            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void start(Event event) {
        EventAttendance.event = event;

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EventAttendance dialog = new EventAttendance(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAttendanceAdd;
    private javax.swing.JButton jButtonAttendanceCreatePerson;
    private javax.swing.JButton jButtonAttendanceDelete;
    private javax.swing.JButton jButtonAttendanceEdit;
    private javax.swing.JComboBox jComboBoxNames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAttendanceDay;
    private javax.swing.JSpinner jSpinnerAttendanceHour;
    private javax.swing.JSpinner jSpinnerAttendanceMinute;
    private javax.swing.JSpinner jSpinnerAttendanceMonth;
    private javax.swing.JSpinner jSpinnerAttendanceYear;
    private javax.swing.JTable jTableAttendance;
    // End of variables declaration//GEN-END:variables
}
