/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.calendar.frontend;

import cz.muni.fi.pv168.calendar.backend.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Properties;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.apache.commons.dbcp.BasicDataSource;

/**
 *
 * @author Jan Smerda, Jiri Stary
 */
public class EventsMainWindow extends javax.swing.JFrame {

    private static final Logger logger =
            Logger.getLogger(EventManagerImpl.class.getName());
    private static EventManagerImpl eventManager;
    private static PersonManagerImpl personManager;
    private static AttendanceManagerImpl attendanceManager;

    public static EventManager getEventManager() {
        return eventManager;
    }

    public static PersonManager getPersonManager() {
        return personManager;
    }

    public static AttendanceManager getAttendanceManager() {
        return attendanceManager;
    }

    /**
     * Creates new form JFrameDesign
     */
    public EventsMainWindow() {
        initComponents();
        jTableEvents.getColumnModel().getColumn(0).setMinWidth(0);
        jTableEvents.getColumnModel().getColumn(0).setMaxWidth(0);
        jTablePeople.getColumnModel().getColumn(0).setMinWidth(0);
        jTablePeople.getColumnModel().getColumn(0).setMaxWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelEvent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEvents = new javax.swing.JTable();
        jButtonEventCreate = new javax.swing.JButton();
        jButtonEventEdit = new javax.swing.JButton();
        jButtonEventSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEventShow = new javax.swing.JButton();
        jButtonEventClear = new javax.swing.JButton();
        jButtonEventDelete = new javax.swing.JButton();
        jSpinnerEventStartDay = new javax.swing.JSpinner();
        jSpinnerEventStartMonth = new javax.swing.JSpinner();
        jSpinnerEventStartYear = new javax.swing.JSpinner();
        jSpinnerEventEndDay = new javax.swing.JSpinner();
        jSpinnerEventEndMonth = new javax.swing.JSpinner();
        jSpinnerEventEndYear = new javax.swing.JSpinner();
        jPanelPeople = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePeople = new javax.swing.JTable();
        jButtonPeopleCreate = new javax.swing.JButton();
        jButtonPeopleEdit = new javax.swing.JButton();
        jButtonPeopleDelete = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTableEvents.setModel(new EventTableModel());
        jScrollPane1.setViewportView(jTableEvents);

        jButtonEventCreate.setText("Create new");
        jButtonEventCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventCreateActionPerformed(evt);
            }
        });

        jButtonEventEdit.setText("Edit selected");
        jButtonEventEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventEditActionPerformed(evt);
            }
        });

        jButtonEventSearch.setText("Search");
        jButtonEventSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Start Date");

        jLabel2.setText("End Date");

        jButtonEventShow.setText("Show attendance");
        jButtonEventShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventShowActionPerformed(evt);
            }
        });

        jButtonEventClear.setText("Clear selection");
        jButtonEventClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventClearActionPerformed(evt);
            }
        });

        jButtonEventDelete.setText("Delete selected");
        jButtonEventDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEventDeleteActionPerformed(evt);
            }
        });

        jSpinnerEventStartDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinnerEventStartMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinnerEventStartYear.setModel(new javax.swing.SpinnerNumberModel(2014, 1970, 2100, 1));

        jSpinnerEventEndDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinnerEventEndMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinnerEventEndYear.setModel(new javax.swing.SpinnerNumberModel(2014, 1970, 2100, 1));

        javax.swing.GroupLayout jPanelEventLayout = new javax.swing.GroupLayout(jPanelEvent);
        jPanelEvent.setLayout(jPanelEventLayout);
        jPanelEventLayout.setHorizontalGroup(
            jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEventLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEventLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEventDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jButtonEventCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEventEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEventLayout.createSequentialGroup()
                                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelEventLayout.createSequentialGroup()
                                        .addGap(219, 219, 219)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanelEventLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonEventShow)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerEventEndDay)
                                    .addComponent(jSpinnerEventStartDay))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEventLayout.createSequentialGroup()
                                        .addComponent(jSpinnerEventStartMonth)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerEventStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelEventLayout.createSequentialGroup()
                                        .addComponent(jSpinnerEventEndMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerEventEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelEventLayout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEventSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEventClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))))
        );
        jPanelEventLayout.setVerticalGroup(
            jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEventLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerEventStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerEventStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerEventStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanelEventLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEventCreate)
                            .addComponent(jButtonEventShow))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEventEdit)
                    .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerEventEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerEventEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerEventEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEventDelete)
                    .addComponent(jButtonEventSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEventClear)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Events", jPanelEvent);

        jTablePeople.setModel(new PersonTableModel());
        jScrollPane2.setViewportView(jTablePeople);

        jButtonPeopleCreate.setText("Create new");
        jButtonPeopleCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeopleCreateActionPerformed(evt);
            }
        });

        jButtonPeopleEdit.setText("Edit selected");
        jButtonPeopleEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeopleEditActionPerformed(evt);
            }
        });

        jButtonPeopleDelete.setText("Delete selected");
        jButtonPeopleDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeopleDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPeopleLayout = new javax.swing.GroupLayout(jPanelPeople);
        jPanelPeople.setLayout(jPanelPeopleLayout);
        jPanelPeopleLayout.setHorizontalGroup(
            jPanelPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeopleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addGroup(jPanelPeopleLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(jPanelPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPeopleCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPeopleEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPeopleDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPeopleLayout.setVerticalGroup(
            jPanelPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeopleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPeopleCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPeopleEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPeopleDelete)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("People", jPanelPeople);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEventCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventCreateActionPerformed
        CreateEditEvent.start(null);
    }//GEN-LAST:event_jButtonEventCreateActionPerformed

    private void jButtonEventEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventEditActionPerformed
        try {
            Event event = new Event();
            event = getEventManager().getEventById((Integer) jTableEvents.getValueAt(jTableEvents.getSelectedRow(), 0));
            CreateEditEvent.start(event);
        } catch (ArrayIndexOutOfBoundsException ex) {
            String msg = "No event is selected.";
            logger.log(Level.SEVERE, msg, ex);
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_jButtonEventEditActionPerformed

    private void jButtonEventDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventDeleteActionPerformed
        try {
            Event event = new Event();
            event = getEventManager().getEventById((Integer) jTableEvents.getValueAt(jTableEvents.getSelectedRow(), 0));
            getEventManager().deleteEvent(event);
            loadEventDatabase();
        } catch (ArrayIndexOutOfBoundsException ex) {
            String msg = "No event is selected.";
            logger.log(Level.SEVERE, msg, ex);
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_jButtonEventDeleteActionPerformed

    private void jButtonEventClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventClearActionPerformed
        loadEventDatabase();
    }//GEN-LAST:event_jButtonEventClearActionPerformed

    private void jButtonEventSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventSearchActionPerformed
        Calendar calStart = new GregorianCalendar((int) jSpinnerEventStartYear.getValue(),
                (int) jSpinnerEventStartMonth.getValue() - 1,
                (int) jSpinnerEventStartDay.getValue());
        Date startDate = calStart.getTime();

        Calendar calEnd = new GregorianCalendar((int) jSpinnerEventEndYear.getValue(),
                (int) jSpinnerEventEndMonth.getValue() - 1,
                (int) jSpinnerEventEndDay.getValue());
        Date endDate = calEnd.getTime();

        loadEventSearch(startDate, endDate);

    }//GEN-LAST:event_jButtonEventSearchActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        loadEventDatabase();
        loadPersonDatabase();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonPeopleCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeopleCreateActionPerformed
        CreateEditPerson.start(null);
    }//GEN-LAST:event_jButtonPeopleCreateActionPerformed

    private void jButtonPeopleDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeopleDeleteActionPerformed
        try {
            Person person = new Person();
            person = getPersonManager().getPersonById((Integer) jTablePeople.getValueAt(jTablePeople.getSelectedRow(), 0));
            getPersonManager().deletePerson(person);
            loadPersonDatabase();
        } catch (ArrayIndexOutOfBoundsException ex) {
            String msg = "No person is selected.";
            logger.log(Level.SEVERE, msg, ex);
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_jButtonPeopleDeleteActionPerformed

    private void jButtonPeopleEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeopleEditActionPerformed
        try {
            Person person = new Person();
            person = getPersonManager().getPersonById((Integer) jTablePeople.getValueAt(jTablePeople.getSelectedRow(), 0));
            CreateEditPerson.start(person);
        } catch (ArrayIndexOutOfBoundsException ex) {
            String msg = "No person is selected.";
            logger.log(Level.SEVERE, msg, ex);
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_jButtonPeopleEditActionPerformed

    private void jButtonEventShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEventShowActionPerformed
        try {
            Event event = new Event();
            event = getEventManager().getEventById((Integer) jTableEvents.getValueAt(jTableEvents.getSelectedRow(), 0));
            EventAttendance.start(event);
        } catch (ArrayIndexOutOfBoundsException ex) {
            String msg = "No event is selected.";
            logger.log(Level.SEVERE, msg, ex);
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_jButtonEventShowActionPerformed

    private void loadEventDatabase() {
        Date startDate = new Date(0L);
        //4136655540000L je hodnota 31.12.2100 v 23:59, tj. nejvyssi cas na spinnerech
        Date endDate = new Date(4136655540000L);
        EventLoadWorker loadWorker = new EventLoadWorker(startDate, endDate);
        loadWorker.execute();
    }

    private void loadEventSearch(Date startDate, Date endDate) {
        EventLoadWorker loadWorker = new EventLoadWorker(startDate, endDate);
        loadWorker.execute();
    }

    private class EventLoadWorker extends SwingWorker<Void, Void> {

        private Date startDate;
        private Date endDate = new Date();

        public EventLoadWorker(Date startDate, Date endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }

        @Override
        protected Void doInBackground() throws Exception {
            EventTableModel model = (EventTableModel) jTableEvents.getModel();
            model.deleteAllEvents();
            List<Event> events = new ArrayList<Event>();
            events = eventManager.findEventsByDate(startDate, endDate);

            for (Event e : events) {
                model.addEvent(e);
            }

            return null;
        }
    }

    public void loadPersonDatabase() {
        PersonLoadWorker personLoadWorker = new PersonLoadWorker();
        personLoadWorker.execute();
    }

    private class PersonLoadWorker extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            PersonTableModel model = (PersonTableModel) jTablePeople.getModel();
            model.deleteAllPersons();
            List<Person> persons = new ArrayList<Person>();
            persons = personManager.findAllPersons();

            for (Person p : persons) {
                model.addPerson(p);
            }

            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        ResourceBundle databaseProperties = ResourceBundle.getBundle("cz.muni.fi.pv168.calendar.common.db");
        
        BasicDataSource ds = new BasicDataSource();
        ds.setUrl(databaseProperties.getString("jdbcUrl"));
        ds.setDriverClassName(databaseProperties.getString("jdbcDriverClassName"));
        ds.setUsername(databaseProperties.getString("jdbcUsername"));
        ds.setPassword(databaseProperties.getString("jdbcPassword"));
        
        personManager = new PersonManagerImpl();
        personManager.setDataSource(ds);
        eventManager = new EventManagerImpl();
        eventManager.setDataSource(ds);
        attendanceManager = new AttendanceManagerImpl();
        attendanceManager.setDataSource(ds);


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventsMainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEventClear;
    private javax.swing.JButton jButtonEventCreate;
    private javax.swing.JButton jButtonEventDelete;
    private javax.swing.JButton jButtonEventEdit;
    private javax.swing.JButton jButtonEventSearch;
    private javax.swing.JButton jButtonEventShow;
    private javax.swing.JButton jButtonPeopleCreate;
    private javax.swing.JButton jButtonPeopleDelete;
    private javax.swing.JButton jButtonPeopleEdit;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelEvent;
    private javax.swing.JPanel jPanelPeople;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerEventEndDay;
    private javax.swing.JSpinner jSpinnerEventEndMonth;
    private javax.swing.JSpinner jSpinnerEventEndYear;
    private javax.swing.JSpinner jSpinnerEventStartDay;
    private javax.swing.JSpinner jSpinnerEventStartMonth;
    private javax.swing.JSpinner jSpinnerEventStartYear;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEvents;
    private javax.swing.JTable jTablePeople;
    // End of variables declaration//GEN-END:variables
}
